development:
  sessions:
    default:
      database: watage_development
      hosts:
        - localhost

test:
  sessions:
    default:
      database: watage_test
      hosts:
        - localhost

production:
  sessions:
    default:
      hosts:
        - - <%= ENV['MONGODB_HOST'] || 'localhost' %>
          - <%= ENV['MONGODB_PORT'] || 27017 %>
      database: <%= ENV['MONGODB_DATABASE'] || 'watage_production' %>
      username: <%= ENV['MONGODB_USERNAME'] %>
      password: <%= ENV['MONGODB_PASSWORD'] %>
      # slaves:
      #   - host: slave1.local
      #     port: 27018
      #   - host: slave2.local
      #     port: 27019
