development:
  sessions:
    default:
      database: watage_development
      hosts:
        - localhost

test:
  sessions:
    default:
      database: watage_test
      hosts:
        -  <%= ENV['WERCKER_MONGODB_HOST'] || 'localhost' %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] || ENV['MONGOLAB_URI'] %>
