development:
  clients:
    default:
      database: watage_development
      hosts:
        -  <%= ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost' %>

test:
  clients:
    default:
      database: watage_test
      hosts:
        -  <%= ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost' %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] || ENV['MONGOLAB_URI'] %>

